language: generic
env:
  global:
  - ORG="devonfw"
  - USER="devonfw-core"
  - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
  - REPO_SOURCE="devon4ng"
  - REPO_DEST="devon4ng.wiki"
  - GH_REPO_SOURCE="github.com/${ORG}/${REPO_SOURCE}.git"
  - GH_REPO_DEST="github.com/${ORG}/${REPO_DEST}.git"
  - secure: Yr8hYx+8y4O33u5vs7reGUzCpltC5r36p4bL5s/7tJxpCZ8TfqKMq0Jgd5xXDzLLkRYb2hPAiyzQw7KHbujKPq3lmelXNoDxtS5HScdBiUXheUcqETZIX3aVEMKn03bK8/y2yyxdhj7yhbll2I5patVfL0cjXusm4ATCN/pPP16vjAfdgCl556P5yY+wQ2tqQK3wr4j08xNZmFxBkfHV94hcsH9rAkEE+DsctBLuD/PSfYYJbTwc0BDXyIYyzswzzQ/BFuUo0PLx9BukEMEPDx0KgGc+oGbpKYz6nTX68+ZeA6oAySeMOU6gQyaeJvCECiggPat+5HMv02CFdpUBZE4QscV6WMnnlfe/E/IfSulF5x0mnQbTJPznCqNvZzZ+wtf+Q9dQUcj5wDfHyofcRcYj+ie+J6D1bVCZimfqs/e46WXVqLUb4jjRE6gJCDZOe9+DacEA58+2qMYeaQGZ1TmheIbIFa9PIOn9XwMRDGGfje/WY+h62yg2O86y1Xw10jVhe7cR2G7KUxiQ2dahHPxqRyO3qA6AseB5CZKXg+ZevdZYegYCDoXkcMspkhJGW4He/HepuTdvFYDfmc29sU9P16nxRZkn+aidvngCw6SDcH+rTelaU4UXnZ2nmvXjAZKYX9Xywzx9GeexLiCpzPdYGK8J6CtpenGkuzKIDtI=
script:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- git clone https://${GH_REPO_SOURCE}
- git clone https://${GH_REPO_DEST}
- yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
- cd ${REPO_DEST}
- pwd
- git remote
- git config user.email ${EMAIL}
- git config user.name ${USER}
- git add .
- git status
- git commit -m "${MESSAGE}"
- git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_DEST}"
- git push origin-wiki master
