name: spellcheck 
on:
  push:
  workflow_dispatch:
jobs:
  spellchecker:
    uses: devonfw/.github/workflows/devonfw-spellchecker.yml@develop
    with:
      RESUSABLE_GH_ACTION_TOKEN: ${{ secrets.RESUSABLE_GH_ACTION_TOKEN }}
