name: spellcheck 
on:
  push:
    paths:
      - '**.asciidoc'
      - '**.md'      
    branches:
      - develop
jobs:
  spellchecker:
    uses: devonfw/.github/.github/workflows/devonfw-sync-docs.yml@master
    secrets:
      RESUSABLE_GH_ACTION_TOKEN: ${{ secrets.GHA_TOKEN }}
